export const types = {
  MOSTRAR_ALERTA: "[AUTH] mostrar alerta",
  OCULTAR_ALERTA: "[AUTH] ocultar alerta",
  LOGIN_ERROR: "[AUTH] login error",
  LOGIN_EXITOSO: "[AUTH] login existoso",
  REGISTRO_EXITOSO: "[AUTH] registro exitoso",
  REGISTRO_ERROR: "[AUTH registro error]",
  OBTENER_USUARIO: "[AUTH] obtener usuario",
  CERRAR_SESION: "[AUTH] cerrar sesion",
  INICIAR_SESION: "[AUTH] inicia sesion",
  USER_CHANGEPHOTO: "[AUTH] USER_CHANGEPHOTO",
  RESET_PASSWORD: "[AUTH] RESET_PASSWORD",
  FIN_AUTENTICACION: "[AUTH] FIN_AUTENTICACION",
  INICIO_AUTENTICACION: "[AUTH] INICIO_AUTENTICACION",
};

export const SHOW_ERRORS_API = "SHOW_ERRORS_API";

//systems
export const GET_ALL_SYSTEMS = "GET_ALL_SYSTEMS";

//courses
export const GET_ALL_COURSES = "GET_ALL_COURSES";
export const GET_ALL_COURSES_PAGINATE = "GET_ALL_COURSES_PAGINATE";
export const GET_LATEST_COURSES = "GET_LATEST_COURSES";
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID";
export const GET_COURSES_BY_SYSTEM_ID = "GET_COURSES_BY_SYSTEM_ID";
export const GET_TOP_TEN_COURSES = "GET_TOP_TEN_COURSES";

//posts
export const SET_SOCKET = "SET_SOCKET";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_REACTIONS = "UPDATE_REACTIONS";
export const SET_POSTS = "SET_POSTS";

export const DELETE_COMMENT = "DELETE_COMMENT";
export const TOOGLE_REACTION = "TOOGLE_REACTION";
export const GET_REACTIONS_SUMMARY = "GET_REACTIONS_SUMMARY";
export const GET_REACTIONS_SUMMARY_MULTIPLE = "GET_REACTIONS_SUMMARY_MULTIPLE";

//user
export const COURSES_COMPLETED_USER = "COURSES_COMPLETED_USER";
export const COURSES_COMPLETED = "COURSES_COMPLETED";
export const GET_TICKETS_BY_USER = "GET_TICKETS_BY_USER";
export const GET_CALENDAR_LINKS = "GET_CALENDAR_LINKS";
export const CALENDAR_ERROR = "CALENDAR_ERROR";
export const CALENDAR_LOADING = "CALENDAR_LOADING";
export const ADD_SHIPPING_ADDRESS = "ADD_SHIPPING_ADDRESS";
export const GET_ADDRESS = "GET_ADDRESS";
export const UPDATE_ADDRESS_SHIPPING = "UPDATE_ADDRESS_SHIPPING";
export const DELETE_ADDRESS_SHIPPING = "DELETE_ADDRESS_SHIPPING";
//EVENTS
export const GET_ALL_EVENTS = "GET_ALL_EVENTS";
export const GET_EVENT_BY_ID = "GET_EVENT_BY_ID";
export const GET_LATEST_EVENTS = "GET_LATEST_EVENTS";

//PRODUCTS
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";

//CART
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const GET_USER_CART = "GET_USER_CART";
export const CLEAR_CART = "CLEAR_CART";
export const SET_GUEST_CART = "SET_GUEST_CART";

//ORDERS
export const CREATE_ORDER = "CREATE_ORDER";
export const ADD_PAYMENT_ORDER = "ADD_PAYMENT_ORDER";
export const DOWNLOAD_ACCOUNT_STATEMENT = "DOWNLOAD_ACCOUNT_STATEMENT";
export const GET_ORDER_USER = "GET_ORDER_USER";

//ORDERS PAYMENTS
export const PARTIAL_PAYMENT = "PARTIAL_PAYMENT";

//LIVES
export const GET_ALL_LIVES = "GET_ALL_LIVES";
export const GET_LATEST_LIVES = "GET_LATEST_LIVES";
export const GET_LIVE_BY_ID = "GET_LIVE_BY_ID";
export const LIVE_STARTED = "LIVE_STARTED";
export const LIVE_ENDED = "LIVE_ENDED";
export const LIVE_STATUS_UPDATE = "LIVE_STATUS_UPDATE";

//SHOPIFY
export const CART_SHOPIFY_CREATED = "CART_SHOPIFY_CREATED";
export const CART_SHOPIFY_LOADING = "CART_SHOPIFY_LOADING";
export const CART_SHOPIFY_UPDATED = "CART_SHOPIFY_UPDATED";
export const CART_SHOPIFY_ERROR = "CART_SHOPIFY_ERROR";
export const CART_SHOPIFY_ADD_LOADING = "CART_SHOPIFY_ADD_LOADING";
export const CART_SHOPIFY_CART_LOADING = "CART_SHOPIFY_CART_LOADING";

//Comunnity
export const GET_POSTS_COMMUNITY = "GET_POSTS_COMMUNITY";
export const CREATE_POST_COMMUNITY = "CREATE_POST_COMMUNITY";
export const CREATE_COMMENT_POST_COMMUNITY = "CREATE_COMMENT_POST_COMMUNITY";
export const TOOGLE_REACTION_POST_COMMUNITY = "TOOGLE_REACTION_POST_COMMUNITY";
export const SOCKET_REACTION_POST_COMMUNITY = "SOCKET_REACTION_POST_COMMUNITY";

//Notifications
export const GET_ALL_NOTIFICATIONS = "GET_ALL_NOTIFICATIONS";
export const COUNT_UNREAD_NOTIFICATIONS = "COUNT_UNREAD_NOTIFICATIONS";
export const MAKE_READ_NOTIFICATION = "MAKE_READ_NOTIFICATION";
export const PUSH_NOTIFICATION = "PUSH_NOTIFICATION";
export const REMOVE_OPTIMISTIC_COMMENT = "REMOVE_OPTIMISTIC_COMMENT";
